### ISSUE TITLE
Forking OctoberCMS

### ISSUE THREAD

**Issue by LukeTowers** [OctoberCMF/october#4]
Unfortunately, due to key differences in vision between the founders and maintainers we have decided to fork OctoberCMS as OctoberCMF. What this means going forwards is that the core team of maintainers (myself, @bennothommo, & @w20k) will no longer be maintaining any @octobercms repositories and will instead be maintaining the @octobercmf repositories.

### Team

Myself, @bennothommo, and @w20k will continue to work on this fork as core maintainers.

### Contact

Feel free to join our Discord here: https://discord.gg/MM3ezTZ and follow our Twitter here: https://twitter.com/OctoberCMF

I have been kicked from the OctoberCMS Slack & Discord.

### Compatibility 

All existing plugins & themes remain compatible with this fork, you will just have to change your composer.json files to reference the following dependencies instead:

```json
"octobercmf/rain": "~1.0",
"octobercmf/system": "~1.0",
"octobercmf/backend": "~1.0",
"octobercmf/cms": "~1.0",
```

**You will still be able to use the OctoberCMS marketplace with OctoberCMF.**

### Future plans

Our immediate goal is to finish setting up the repos under the OctoberCMF name, the system, backend, & cms repos are being setup as I type this and should be ready by end of day today.

If there are any pending PRs / issues on the OctoberCMS repos that you would like dealt with, please resubmit them here.

Once that is complete we will be focusing on finishing up the remaining work for Build 460 and getting these changes pushed to master with the Laravel 6 update to follow afterwards.

Moving forwards we will continue to work on new builds as per normal and we will also start work on the main website for the project with the goal of eventually replacing the OctoberCMS marketplace. In the meantime, you will still be able to use the OctoberCMS marketplace with OctoberCMF.

Our big picture goal is to continue to grow and improve and eventually take over WordPress as the CMS of choice around the world. I would like to thank everyone for their patience and understanding as we move forwards and I look forward to all the excellent work that is to come!

**Comment by LukeTowers** [comment]
## FAQs:

### Have you been paid for your role as a maintainer?

Yes, I have received a portion of the revenue generated from the project over the past three years; however that has amounted to a grand total of $7,863.13. I would estimate that I've put in approximately ~3000 hours which roughly works out to $2.62 / hour. However, the other maintainers (@bennothommo & @w20k) are completely volunteer.

### You wanted access to the servers?

Yes, I've been asking @daftspunk for access to the marketplace codebase for a couple years now in order to help with the maintenance and support aspects of that side of the project. However, it has always been denied with the response that it is solely @alekseybobkov's realm.

### Will my plugins & themes still work?

Yes, you will still be able to use your existing plugins and themes with OctoberCMF going forward. All you have to do is update your composer dependencies to point to our repositories instead. 

### Will the marketplace still work?

Yes, you can continue using the octobercms.com marketplace to manage your projects, plugins, and themes. However at some point in the future we will be building a new version that will diverge from the main marketplace

### Was this planned all along?

No. I've been wanting to continue to improve this project since I started, and have always had the goal of being able to work on it full time. However, over the past few months it has become clear that my vision for the project was incompatible with @daftspunk's so in October I purchased octobercmf.com in case we were not able to come to agreement and I had to fork.

**Comment by amp9020** [comment]
Per instructions, adding the following comments to review  in the future:

Will there be a migration tool for existing OctCMS installs?

Also will CMF be listed in Softaculous ? Many shared hosted Cpanels have OctCMS listed and it would be beneficial to have CMF listed or available.

**Comment by fresswolf** [comment]
You said you want to overtake wordpress but then renamed the project to content management framework. Isn’t that contradicting? Would be interesting to read about some long term goals/roadmap you guys envision with the project.

**Comment by bennothommo** [comment]
@amp9020 @fresswolf At this stage, @LukeTowers has entered talks with the founders of October CMS to see if there can be a reconcilliation that was make this fork unnecessary and the maintainer team continues working with the original October CMS codebase. If that ends up not being the case, we'll be happy to answer those questions.

**Comment by LukeTowers** [comment]
Closed by https://github.com/OctoberCMF/october/issues/9
